#!/bin/bash

pushd ~/dba/oid >/dev/null

for s in services/*.ldif; do
  S=$(basename "$s")
  S=${S%.ldif}
  oid_add_service "$S"
done

grep -v '^#' realms.lst | while read -r r; do
  for s in "$r"/services/*.ldif; do
    S=$(basename "$s")
    S=${S%.ldif}
    oid_add_service "$S" "$r"
  done
done

popd >/dev/null
