#!/bin/bash
pushd ~/dba/oid >/dev/null

source ./oid.params

REALM=$(echo "$1" | tr '[:upper:]' '[:lower:]')
if [ -n "$REALM" ]; then
  DC=",dc=$REALM"
  mkdir -p "$REALM"/aliases
  echo "== Getting aliases for \"$REALM\" context"
else
  REALM=.
  echo "== Getting aliases for default context"
fi

PATH=$ORACLE_HOME/bin:$PATH

ldapsearch -L -h "$OID_HOST" -p "$OID_PORT" -b "${OID_CONTEXT}${DC}" $OPT '(objectclass=orclNetServiceAlias)' cn | grep -E '^cn:' | awk '{print($2)}' | sort > "$REALM"/aliases.lst
# get ldifs for aliases
find "$REALM"/aliases -name '*.ldif' -type f -delete
grep -v '^#' "$REALM"/aliases.lst | while read -r S; do
  echo "Get description for alias $S ..."
  ldapsearch -LLL -T createtimestamp -h "$OID_HOST" -p "$OID_PORT" -b "cn=$S,${OID_CONTEXT}${DC}" $OPT '(objectclass=*)' | perl -0777pe 's/\n //g' | sed -r '/^authpassword/d;s/,[ \t]*cn=/,cn=/g;s/[ \t]+$//g' > "$REALM/aliases/$S.ldif"
done

popd >/dev/null
